### PR TITLE
Fix unchecked `menu edit` commands

### LINKED ISSUE #257: Orders can be rendered unfulfillable if dish item is edited after order is placed

### PR DESCRIPTION
**Pull request by creativequotient**
Fix #257 

Sufficiency in inventory was only checked during order add, allowing users to edit menu items after additions, resulting in inability to complete orders based on stock.

With this update, whenever a menu item is to be edited, only if there is sufficient stock to complete orders after this change will the edit pass.

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -488,14 +488,24 @@ public void cancelOrders(List<Order> targets) {
...
-                if (!ingredientsTable.containsKey(d.getKey())) {
-                    ingredientsTable.put(d.getKey(), 0);
+        for (Order target : orders) {
+            List<Pair<Dish, Integer>> dishesList = target.getDishQuantityList();
+            for (Pair<Dish, Integer> p : dishesList) {
+                for (Pair<Ingredient, Integer> d : p.getKey().getIngredientQuantityList()) {
+                    if (!ingredientsTable.containsKey(d.getKey())) {
+                        ingredientsTable.put(d.getKey(), 0);
+                    }
+                    ingredientsTable.put(d.getKey(), ingredientsTable.get(d.getKey()) + d.getValue() * p.getValue());
```
Comment (Sharptail) [inline src/main/java/seedu/address/model/ModelManager.java]: It might be good to reduce the deep nested loop here for code quality purposes stated [here](https://nus-cs2103-ay2021s2.github.io/website/se-book-adapted/chapters/codeQuality.html#avoid-deep-nesting)

**Review by IanCKW — APPROVED** [review]
lgtm

**Review by Sharptail — APPROVED** [review]
LGTM
